name: autorelease

on:
  push:
    tags: ["v*"]
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - run: mise run install

      - run: mise run codegen

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> "$GITHUB_OUTPUT"

      - name: Create PR if changes
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update generated code"
          title: "chore: update generated code"
          body: "This PR updates the generated code."
          branch: "chore/codegen-update"
          base: ${{ github.head_ref || github.ref_name }}

      - run: mise run ci
        if: steps.git-check.outputs.changes != 'true'

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
